morse_dict = {'a': ' ⚪ ➖  ',
              'b': ' ➖ ⚪ ⚪ ⚪  ',
              'c': ' ➖ ⚪ ➖ ⚪  ',
              'd': ' ➖ ⚪ ⚪  ',
              'e': ' ⚪  ',
              'f': ' ⚪ ⚪ ➖ ⚪  ',
              'g': ' ➖ ➖ ⚪  ',
              'h': ' ⚪ ⚪ ⚪ ⚪  ',
              'i': ' ⚪ ⚪  ',
              'j': ' ⚪ ➖ ➖ ➖  ',
              'k': ' ➖ ⚪ ➖  ',
              'l': ' ⚪ ➖ ⚪ ⚪  ',
              'm': ' ➖ ➖  ',
              'n': ' ➖ ⚪  ',
              'o': ' ➖ ➖ ➖  ',
              'p': ' ⚪ ➖ ➖ ⚪  ',
              'q': ' ➖ ➖ ⚪ ➖  ',
              'r': ' ⚪ ➖ ⚪  ',
              's': ' ⚪ ⚪ ⚪  ',
              't': ' ➖  ',
              'u': ' ⚪ ⚪ ➖  ',
              'v': ' ⚪ ⚪ ⚪ ➖  ',
              'w': ' ⚪ ➖ ➖  ',
              'x': ' ➖ ⚪ ⚪ ➖  ',
              'y': ' ➖ ⚪ ➖ ➖  ',
              'z': ' ➖ ➖ ⚪ ⚪  ',
              '1': ' ⚪ ➖ ➖ ➖ ➖  ',
              '2': ' ⚪ ⚪ ➖ ➖ ➖  ',
              '3': ' ⚪ ⚪ ⚪ ➖ ➖  ',
              '4': ' ⚪ ⚪ ⚪ ⚪ ➖  ',
              '5': ' ⚪ ⚪ ⚪ ⚪ ⚪  ',
              '6': ' ➖ ⚪ ⚪ ⚪ ⚪  ',
              '7': ' ➖ ➖ ⚪ ⚪ ⚪  ',
              '8': ' ➖ ➖ ➖ ⚪ ⚪  ',
              '9': ' ➖ ➖ ➖ ➖ ⚪  ',
              '0': ' ➖ ➖ ➖ ➖ ➖  ',
              '.': ' ⚪ ➖ ⚪ ➖ ⚪ ➖  ',
              ',': ' ➖ ➖ ⚪ ⚪ ➖ ➖  ',
              ':': ' ➖ ➖ ➖ ⚪ ⚪ ⚪  ',
              '-': ' ➖ ⚪ ⚪ ⚪ ⚪ ➖  ',
              "'": ' ⚪ ➖ ➖ ➖ ➖ ⚪  ',
              '/': ' ➖ ⚪ ⚪ ➖ ⚪  ',
              '[': ' ➖ ⚪ ➖ ➖ ⚪ ➖  ',
              ']': ' ➖ ⚪ ➖ ➖ ⚪ ➖  ',
              '?': ' ⚪ ⚪ ➖ ➖ ⚪ ⚪  ',
              '!': ' ➖ ⚪ ➖ ⚪ ➖ ➖  '
              }
translate_phrase = input("What would you like translated to Morse Code?\n").lower()
translate_phrase = translate_phrase.replace(' ', '    ')
for character in translate_phrase:
    if character in morse_dict:
        translate_phrase = translate_phrase.replace(character, morse_dict[character])
print(f"Here is your translation in Morse:\n{translate_phrase}")
